# Generated by Django 2.0.13 on 2019-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='player1',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='player2',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='player3',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
