# Generated by Django 2.0.13 on 2019-04-04 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=200)),
                ('position', models.CharField(default='None', max_length=200)),
                ('goals', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('owngoals', models.PositiveIntegerField()),
                ('cleansheets', models.PositiveIntegerField()),
                ('yellowcards', models.PositiveIntegerField()),
                ('redcards', models.PositiveIntegerField()),
                ('motms', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='None', max_length=200)),
                ('player1', models.CharField(default='None', max_length=200)),
                ('player2', models.CharField(default='None', max_length=200)),
                ('player3', models.CharField(default='None', max_length=200)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
